### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mkerfoot** [logicmonitor/docker_lm_collector#13]
Can you help me debug this error?

PS K:\> docker logs lm
DEBUG:root:Instantiating LogicMonitor object
DEBUG:root:Running Collector._get...
DEBUG:root:Running LogicMonitor.get_collectors...
DEBUG:root:Making RPC call to 'getAgents'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Collectors returned
DEBUG:root:Installing collector.
DEBUG:root:Running Collector.create...
DEBUG:root:Running Collector._create...
DEBUG:root:Platform is Linux
DEBUG:root:Running Collector._get...
DEBUG:root:Running LogicMonitor.get_collectors...
DEBUG:root:Making RPC call to 'getAgents'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Collectors returned
DEBUG:root:System changed
DEBUG:root:Making RPC call to 'addAgent'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Running Collector.get_installer_binary...
DEBUG:root:64 bit system
DEBUG:root:Platform is Linux
DEBUG:root:Agent ID is 9
DEBUG:root:Looking for existing installer at /usr/local/logicmonitor/logicmonitorsetup9_64.bin
DEBUG:root:No previous installer found
DEBUG:root:System changed
DEBUG:root:Downloading installer file
DEBUG:root:Running LogicMonitor.do...
DEBUG:root:Attempting to open URL: https://virtevasandbox.logicmonitor.com/santaba/do/logicmonitorsetup?arch=64&id=9&
DEBUG:root:Running Collector.install...
DEBUG:root:Platform is Linux
DEBUG:root:Running Collector.get_installer_binary...
DEBUG:root:64 bit system
DEBUG:root:Platform is Linux
DEBUG:root:Agent ID is 9
DEBUG:root:Looking for existing installer at /usr/local/logicmonitor/logicmonitorsetup9_64.bin
DEBUG:root:Collector installer already exists
DEBUG:root:System changed
DEBUG:root:Setting installer file permissions
DEBUG:root:Executing installer
DEBUG:root:*************** Notice ******************************
The installer will verify the total physical memory available based on the collector size selected.
A small collector will use up to 1GB memory, requires 2GB total physical memory.
A medium collector will use up to 2GB memory, requires 4GB total physical memory.
A large collector will use up to 4GB memory, requires 8GB total physical memory.
*****************************************************
Extracting installer files ...
Extracting bundled JRE files ...
Insufficient physical memory. please choose a proper collector size installer.
Installation aborted.
WARNING:root:Error: Unable to install collector: 
Error: Unable to install collector: 
DEBUG:root:Instantiating Collector object
DEBUG:root:Instantiating LogicMonitor object
DEBUG:root:Running Collector._get...
DEBUG:root:Running LogicMonitor.get_collectors...
DEBUG:root:Making RPC call to 'getAgents'
DEBUG:root:Running LogicMonitor.rpc
DEBUG:root:RPC call succeeded
DEBUG:root:Collectors returned
DEBUG:root:Collector already installed.
DEBUG:root:Cleaning any existing lock files.
DEBUG:root:Starting collector.
DEBUG:root:Running Collector.start
DEBUG:root:Platform is Linux
DEBUG:root:Retrieving status of service logicmonitor-agent
DEBUG:root:Getting service logicmonitor-agent control type
DEBUG:root:Service control is via init.d
Traceback (most recent call last):
  File "/startup.py", line 98, in <module>
    main()
  File "/startup.py", line 87, in main
    startup(params)
  File "/startup.py", line 45, in startup
    collector.start()
  File "/usr/local/lib/python2.7/site-packages/logicmonitor_core/Collector.py", line 220, in start
    output = Service.getStatus("logicmonitor-agent")
  File "/usr/local/lib/python2.7/site-packages/logicmonitor_core/Service.py", line 22, in getStatus
    stdout=subprocess.PIPE))
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by woz5999** [comment]
@mkerfoot This error is caused by a confluence of a few things:

- Newer collector versions are now available in different memory configurations and are aware of the current system memory size
- This version of the collector container uses our older RPC API which does not support selecting collector memory configuration size
- Your system doesn't appear to have enough memory available for the default collector size

You can avert this issue in two ways:
- Run this image on a host with more physical memory 
- This image is being deprecated in favor of a newer image that utilizes our newer RESTful API and provides greater configuration flexibility. If you use the image here, https://hub.docker.com/r/logicmonitor/collector, you'll be able to specify a collector size at startup to better suit the host the container is running on.
