### ISSUE TITLE
Exit Status 159

### ISSUE THREAD

**Issue by VNerdIO** [logicmonitor/docker_lm_collector#36]
Testing on a raspberrypi, and unable to get the collector running. id/key are correct and used for powershell automation testing, just obscured here. Docker logs doesn't return anything.

sudo docker run --name $NAME -d -e account=cspire -e access_id="XXXX" -e access_key="XXXX" -e collector_size=nano logicmonitor/collector:latest
abed3986f62b62172b95468532b5f3596ff462c4d463732791fc31ad92d6f25d

sudo docker container ls -a
CONTAINER ID        IMAGE                           COMMAND             CREATED             STATUS                        PORTS               NAMES
abed3986f62b        logicmonitor/collector:latest   "/entrypoint.sh"    15 seconds ago      Exited (159) 15 seconds ago                       csb-b17ed

sudo docker logs abed3986f62b

**Comment by woz5999** [comment]
The LogicMonitor collector and collector docker image are not able to run on ARM architectures.

**Comment by VNerdIO** [comment]
Gotcha, thanks
